services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - port-net
    labels:
      caddy: $MY_URL
      caddy.handle_path: "/portainer*"
      caddy.handle_path.reverse_proxy: "{{upstreams http 9000}}"
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
    data:

networks:
  port-net:
    external: true
    name: $DOCKER_MY_NETWORK
