services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    #labels:
    #  caddy:
    #  caddy.https_port: 61001
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=homelab-network
    networks:
      - homelab-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../services/caddy/caddy_data:/data
    restart: unless-stopped

volumes:
  caddy_data: {}
