services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - homelab-network
    labels:
      caddy: $MY_URL
      caddy.redir: /jellyfin /jellyfin/
      caddy.reverse_proxy: "/jellyfin/* {{upstreams http 8096}}"
    volumes:
      - ../../services/jellyfin/config:/config
      - ../../services/jellyfin/cache:/cache
      - $HDD_MOUNT:/media/:ro
    ports:
      - "8096:8096"
      - "1900:1900/udp"
